// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiboOZf2lEEWFAIuQplDt6h9m5d0Oxfc8',
    appId: '1:410235314749:web:1edbd9f6c9f24eb782c054',
    messagingSenderId: '410235314749',
    projectId: 'cheatsheet-770ad',
    authDomain: 'cheatsheet-770ad.firebaseapp.com',
    storageBucket: 'cheatsheet-770ad.appspot.com',
    measurementId: 'G-KVV4GRWZD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_dzqITCi5btoE7bZaVqHD4IjbrDX-_cI',
    appId: '1:410235314749:android:b4b840f878bf84e382c054',
    messagingSenderId: '410235314749',
    projectId: 'cheatsheet-770ad',
    storageBucket: 'cheatsheet-770ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgGd1IauxMNzLt-7oBEnm6vP426P9_vdQ',
    appId: '1:410235314749:ios:9400cea7b7202a0a82c054',
    messagingSenderId: '410235314749',
    projectId: 'cheatsheet-770ad',
    storageBucket: 'cheatsheet-770ad.appspot.com',
    iosClientId:
        '410235314749-ddspkomr2c5lql1lldfomvk6gs3j1bt0.apps.googleusercontent.com',
    iosBundleId: 'com.example.cheatSheet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgGd1IauxMNzLt-7oBEnm6vP426P9_vdQ',
    appId: '1:410235314749:ios:9400cea7b7202a0a82c054',
    messagingSenderId: '410235314749',
    projectId: 'cheatsheet-770ad',
    storageBucket: 'cheatsheet-770ad.appspot.com',
    iosClientId:
        '410235314749-ddspkomr2c5lql1lldfomvk6gs3j1bt0.apps.googleusercontent.com',
    iosBundleId: 'com.example.cheatSheet',
  );
}
